version: '3.8'

services:
  quantum-receptionist:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_HEYGEN_API_KEY=${VITE_HEYGEN_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    networks:
      - quantum-network

networks:
  quantum-network:
    driver: bridge